Synchronisation des organisations avec des groupes Outline
numerique-gouv/secretariat pull request #14
Opened 2023-10-19 15:04 UTC by tut-tuuut

## 🎯 Objectif

- Quand on crée une organisation : on crée un groupe du même nom sur Outline
- Quand on ajoute un utilisateur à une orga : on ajoute l'utilisateur au groupe outline (et synchro quand on sort un utilisateur d'une orga)

## 🔍 Implémentation

- Compléter le client
- Faire le nécessaire dans les méthodes save_model() de l'admin

## ⚠️ Informations supplémentaires

_(optionnel) Documentation, commandes à lancer, variables d'environnement, etc._

## 🏕 Amélioration continue

- _(optionnel) Une liste d'autres modifications pas en lien direct avec la PR_

## 🖼️ Images

_(optionnel) Une ou plusieurs captures d'écran, si pertinent_

2023-10-19 15:06 UTC, tut-tuuut commented on secretariat/utils/outline.py
> +            )
Je suis allée un peu plus loin que pour les autres méthodes, puisque ici Outline nous disait explicitement ce qui n'allait pas !

2023-10-24 14:34 UTC, tut-tuuut commented on secretariat/models.py
> +    def synchronize_to_outline(self):
J'ai finalement appelé cette méthode `synchronize_to_outline` pour noter qu'en effet on envoie des choses _vers_ Outline. Je ne l'ai pas appelé "push" car on garde quand même l'uuid qui est sauvegardé sur l'objet : ce n'est pas un "push" bête et méchant.

2023-10-24 15:04 UTC, tut-tuuut commented on secretariat/tests/test_outline_client.py
> +    def test_invite_already_invited_user(self, mock_post):
J'ai ajouté de la robustesse et des tests sur tous les cas d'erreur que j'ai rencontré en une seule après-midi. Ça fait beaucoup de tests. XD

2023-10-25 11:50 UTC, mjeammet commented on secretariat/tests/test_outline_client.py
> +        self.assertTrue(mock_post.called, "The client should send a POST request")
Trop cool tout ça mais je me souviens plus pourquoi on fait partout le dernier test sur le POST.

2023-10-25 11:51 UTC, mjeammet commented on secretariat/tests/test_outline_client.py
> +            client.create_new_group("Oh le joli groupe ENCORE")
😁

2023-10-25 11:54 UTC, mjeammet commented on secretariat/tests/test_user_synchronization.py
> +    OUTLINE_API_TOKEN and OUTLINE_API_URL and OUTLINE_OPI_GROUP_ID,
Est-ce que on renomme OUTLINE_OPI_GROUP_ID en OUTLINE_TEST_something ?

2023-10-25 11:57 UTC, mjeammet commented on secretariat/utils/outline.py
> -        self.status_code = error_code
Pourquoi supprimer ça ?

2023-10-25 11:57 UTC, mjeammet commented on secretariat/utils/outline.py
> -        self.status_code = error_code
OK, là c'est 200 donc ça indique rien de spécial de le renvoyer.

2023-10-25 12:02 UTC, mjeammet reviewed
Très cool. On a laissé quelques commentaires !

2023-10-25 12:24 UTC, tut-tuuut commented on secretariat/tests/test_user_synchronization.py
> +    OUTLINE_API_TOKEN and OUTLINE_API_URL and OUTLINE_OPI_GROUP_ID,
bonne idée !

2023-10-25 12:25 UTC, tut-tuuut commented on secretariat/utils/outline.py
> -        self.status_code = error_code
J'en étais à 3 copier-coller alors j'ai déplacé la méthode sur la classe mère.

2023-10-25 12:33 UTC, tut-tuuut commented on secretariat/tests/test_outline_client.py
> +        self.assertTrue(mock_post.called, "The client should send a POST request")
Ça sert à vérifier que quelque chose, quelque part, a effectué une requête POST à l'aide du module `request` dont il se trouve que je l'ai détourné pour qu'il ne fasse pas des vraies requêtes mais retourne quand même des choses qui ressemblent à des vraies réponses.
Ça sert aussi à vérifier que le mock sert à quelque chose : si je fais le mock et qu'à la fin on ne l'a pas appelé, autant le supprimer.

2023-10-25 12:35 UTC, tut-tuuut commented on secretariat/tests/test_outline_client.py
> +        self.assertTrue(mock_post.called, "The client should send a POST request")
Si je reformule comme ça, c'est plus clair ?

```suggestion
        self.assertTrue(mock_post.called, "A POST request should have been sent at some point")
```

2023-10-25 13:34 UTC, mjeammet commented on secretariat/tests/test_outline_client.py
> +        self.assertTrue(mock_post.called, "The client should send a POST request")
Ah oui, un peu plus !

2023-10-25 13:35 UTC, mjeammet commented on secretariat/utils/outline.py
> -        self.status_code = error_code
Ah oui j'avais pas vu la subtilité. Top

2023-10-25 13:36 UTC, mjeammet commented on secretariat/tests/test_user_synchronization.py
> +    OUTLINE_API_TOKEN and OUTLINE_API_URL and OUTLINE_OPI_GROUP_ID,
on fait ça dans une PR à part ou ici ? Tu voulais qu'on approuve celle-là vite pour bosser sereinement sur les 2 en cours ?

2023-10-25 14:05 UTC, tut-tuuut commented on secretariat/tests/test_user_synchronization.py
> +    OUTLINE_API_TOKEN and OUTLINE_API_URL and OUTLINE_OPI_GROUP_ID,
je pense qu'on va faire à part, je commence à être perdue dans les PR qui sont ouvertes !

2023-10-25 14:05 UTC, tut-tuuut commented on secretariat/tests/test_outline_client.py
> +        self.assertTrue(mock_post.called, "The client should send a POST request")
OK, je corrige :)

2023-10-25 14:08 UTC, mjeammet requested changes

2023-10-25 14:08 UTC, mjeammet commented on secretariat/tests/test_user_synchronization.py
> +    def test_add_user_to_outline(self):
Ah tiens, y a ce test qui casse en fait.

2023-10-25 14:09 UTC, mjeammet commented on secretariat/tests/test_user_synchronization.py
> +    def test_add_user_to_outline(self):
Je jette un oeil.

2023-10-25 14:19 UTC, tut-tuuut commented on secretariat/tests/test_user_synchronization.py
> +    def test_add_user_to_outline(self):
Si tu veux une piste de recherche, je sais que parfois ça coince parce que ma userFactory() génère des adresses mail contenant des accents… Et après je relance le test et on tombe sur un mail valide et ça passe. #lazyDrivenDevelopment

2023-10-25 14:33 UTC, mjeammet commented on secretariat/tests/test_user_synchronization.py
> +    def test_add_user_to_outline(self):
Oh woaw effectivement ce sont des Invalid emails. Est-ce que ce serait ça ? 

J'ai trouvé un package qui enlève les accents, je pousse ça.

2023-10-25 14:37 UTC, mjeammet commented on secretariat/tests/test_user_synchronization.py
> +    def test_add_user_to_outline(self):
typiquement un package qu'on pourra mettre dans les tests et pas dans la prod quand on utilisera poetry !

2023-10-25 15:11 UTC, mjeammet approved these changes

2023-10-25 15:14 UTC, merged